name: osme
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
    # Core numerics, data manipulation
  - numpy
  - pandas
  - polars
  - pyarrow
  - scipy
  - scikit-learn
  - statsmodels

  # Geospatial packages
  - geopandas
  - netcdf4
  - cftime
  - pyproj
  - shapely
  - xarray

  # Visualization
  - matplotlib

  # Utilities
  - ipykernel
  - jupyter
  - requests
  - tqdm

    # Dev tools available on conda-forge
  - black
  - ruff
  - pytest
  - pytest-cov
  - pre-commit
  - build

   # Documentation tools available on conda-forge
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python

  - pip:
      # editable installs for local packages

      - -e .
      # - -e packages/weather_data_retrieval
      # - -e packages/grid_data_retrieval
      # - -e packages/data_cleaning_and_joining
      # - -e packages/marginal_emissions_modelling
      # - -e packages/osme_common

      # dependencies
      - cdsapi

      # documentation tools
      - mkdocstrings
      - mkdocs-awesome-pages-plugin