# marginal_emissions_modelling mkdocs.yml
site_name: OSME - Marginal Emissions Modelling - Documentation
docs_dir: docs

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Codebase: codebase.md
